esphome:
  name: esp32-balkon

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api-encryption-key
ota:
  password: !secret ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-balkon"
    password: !secret ap_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

deep_sleep:
  run_duration: 5min
  sleep_duration: 5min
  id: deep_sleep1

sensor:
  - platform: homeassistant
    name: "Moisture Set Point"
    entity_id: input_number.desired_moisture1
    id: moisture_set
    accuracy_decimals: 0
  
  - platform: homeassistant
    name: "Sleep Time"
    entity_id: input_number.desired_sleeptime1
    id: sleeptime_set
  
  - platform: template
    name: "Pump1 last watered"
    device_class: timestamp
    id: pump1_last_update

  - platform: adc # airdry: 2,543V; waterwet: 1,023V
    pin: 36
    name: "soil Moisture"
    id: moisturesensor
    attenuation: 11db
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 5s
    filters:
    - median:   #median over the last 7 values
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear: #setting the voltage values to equalent percentages
        - 2.543 -> 0.00 
        - 1.023 -> 100.00 
     #limit the value to 0 and 100%
    - lambda: |-
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);
    on_value:
      then:
        - if:
            condition:  #check that the threshold value from HA UI is imported
              sensor.in_range:
                id: moisture_set
                below: 100.0
            then:
              - if:
                  condition:  #compare value from sensor with threshold value, it is more complicated that "on_range" bcs it also triggers now when the value didnt changed
                    lambda: 'return id(moisturesensor).state < id(moisture_set).state;'
                  then:
                  - deep_sleep.prevent: deep_sleep1
                  - switch.turn_on: pump1
                  - delay: 10s
                  - switch.turn_off: pump1
                  - sensor.template.publish: #sending Timestamp of pumping to HA UI                                                                                                                                 
                      id: pump1_last_update                                                                                                                                                   
                      state: !lambda 'return id(homeassistant_time).now().timestamp;'
                  - if:
                      condition: #prevent esp32 from entering deep_sleep for updating purpose
                        binary_sensor.is_on: preventdeepsleep_set
                      then:
                      - deep_sleep.prevent: deep_sleep1
                      else:
                      - deep_sleep.enter:
                          id: deep_sleep1
                          sleep_duration: 2min
                  else:
                  - switch.turn_on: LED2
                  - delay: 15s 
                  - switch.turn_off: LED2
                  - if:
                      condition: #prevent esp32 from entering deep_sleep for updating purpose
                        binary_sensor.is_on: preventdeepsleep_set
                      then:
                      - deep_sleep.prevent: deep_sleep1
                      else:
                      - deep_sleep.enter:
                          id: deep_sleep1
                          sleep_duration: !lambda 'return id(sleeptime_set).state*60000;' #for converting in min *60000, for converting in h *3600000



binary_sensor:
  - platform: homeassistant 
    name: "prevent deep_sleep"
    entity_id: input_boolean.prevent_deep_sleep
    id: preventdeepsleep_set

switch:
  - platform: gpio
    pin: 22
    name: "pumping"
    id: pump1
    restore_mode: ALWAYS_OFF
    icon: "mdi:water-pump"

  - platform: gpio
    pin: 23
    name: "running"
    id: LED1
    inverted: true

  - platform: gpio
    pin: 14
    name: "status"
    id: LED2
    restore_mode: ALWAYS_OFF
